import type { DriverKind } from "@queryx/shared";

export interface ExplainQuery {
  sql: string;
}

export interface ExplainAnalyzeQuery {
  sql: string;
  warning: string;
}

export interface ExplainQueryError {
  message: string;
}

export type ExplainQueryResult =
  | { ok: true; query: ExplainQuery }
  | { ok: false; error: ExplainQueryError };

export type ExplainAnalyzeQueryResult =
  | { ok: true; query: ExplainAnalyzeQuery }
  | { ok: false; error: ExplainQueryError };

/**
 * Build a non-executing EXPLAIN statement for one SQL document.
 * EXPLAIN ANALYZE is intentionally not generated by this helper.
 */
export function buildExplainQuery(sql: string): ExplainQueryResult {
  const statement = sql.trim();
  const executableStatement = withoutLeadingComments(statement).trim();
  if (!statement) {
    return { ok: false, error: { message: "Enter SQL before explaining it" } };
  }

  if (/^EXPLAIN\b/i.test(executableStatement)) {
    return {
      ok: false,
      error: {
        message:
          "Remove the existing EXPLAIN prefix; QueryX adds a safe non-ANALYZE plan wrapper",
      },
    };
  }

  if (hasMultipleStatements(statement)) {
    return {
      ok: false,
      error: {
        message: "Explain one SQL statement at a time",
      },
    };
  }

  return { ok: true, query: { sql: `EXPLAIN ${statement}` } };
}

export function buildExplainAnalyzeQuery(
  sql: string,
  driver: DriverKind,
): ExplainAnalyzeQueryResult {
  const statement = sql.trim();
  const executableStatement = withoutLeadingComments(statement).trim();
  if (!statement) {
    return { ok: false, error: { message: "Enter SQL before explaining it" } };
  }
  if (/^EXPLAIN\b/i.test(executableStatement)) {
    return {
      ok: false,
      error: {
        message:
          "Remove the existing EXPLAIN prefix; QueryX adds the ANALYZE wrapper",
      },
    };
  }
  if (hasMultipleStatements(statement)) {
    return {
      ok: false,
      error: { message: "Explain one SQL statement at a time" },
    };
  }
  if (driver !== "postgres" && driver !== "mysql") {
    return {
      ok: false,
      error: {
        message: `EXPLAIN ANALYZE is not supported for ${driver === "sqlite" ? "SQLite" : driver === "sqlserver" ? "SQL Server" : "Oracle"}`,
      },
    };
  }
  const wrappedSql =
    driver === "postgres"
      ? `EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT) ${statement}`
      : `EXPLAIN ANALYZE ${statement}`;
  return {
    ok: true,
    query: {
      sql: wrappedSql,
      warning:
        "EXPLAIN ANALYZE executes the statement and may change database state",
    },
  };
}

function withoutLeadingComments(sql: string): string {
  let remaining = sql;
  while (true) {
    remaining = remaining.trimStart();
    if (remaining.startsWith("--")) {
      const newline = remaining.indexOf("\n");
      remaining = newline === -1 ? "" : remaining.slice(newline + 1);
      continue;
    }
    if (remaining.startsWith("/*")) {
      const end = remaining.indexOf("*/", 2);
      remaining = end === -1 ? "" : remaining.slice(end + 2);
      continue;
    }
    return remaining;
  }
}

function hasMultipleStatements(sql: string): boolean {
  let quote: "single" | "double" | "backtick" | null = null;
  let lineComment = false;
  let blockComment = false;
  let escaped = false;
  let semicolonSeen = false;

  for (let index = 0; index < sql.length; index += 1) {
    const character = sql[index];
    const next = sql[index + 1];

    if (lineComment) {
      if (character === "\n") lineComment = false;
      continue;
    }
    if (blockComment) {
      if (character === "*" && next === "/") {
        blockComment = false;
        index += 1;
      }
      continue;
    }
    if (quote) {
      if (escaped) {
        escaped = false;
        continue;
      }
      if (character === "\\" && quote !== "double") {
        escaped = true;
        continue;
      }
      if (character === quoteCharacter(quote)) {
        if (sql[index + 1] === character) {
          index += 1;
        } else {
          quote = null;
        }
      }
      continue;
    }

    if (character === "-" && next === "-") {
      lineComment = true;
      index += 1;
      continue;
    }
    if (character === "/" && next === "*") {
      blockComment = true;
      index += 1;
      continue;
    }
    if (character === "'") {
      quote = "single";
      continue;
    }
    if (character === '"') {
      quote = "double";
      continue;
    }
    if (character === "`") {
      quote = "backtick";
      continue;
    }
    if (character === ";") {
      if (semicolonSeen) return true;
      semicolonSeen = true;
      continue;
    }
    if (semicolonSeen && !/\s/.test(character)) return true;
  }

  return false;
}

function quoteCharacter(quote: "single" | "double" | "backtick"): string {
  if (quote === "single") return "'";
  if (quote === "double") return '"';
  return "`";
}
